const actionTypes = {
PRODUCT_LIST_REQUEST: 'PRODUCT_LIST_REQUEST',
PRODUCT_LIST_SUCCESS: 'PRODUCT_LIST_SUCCESS',
PRODUCT_LIST_FAIL: 'PRODUCT_LIST_FAIL',
PRODUCT_DETAILS_REQUEST: 'PRODUCT_DETAILS_REQUEST',
PRODUCT_DETAILS_SUCCESS: 'PRODUCT_DETAILS_SUCCESS',
PRODUCT_DETAILS_FAIL: 'PRODUCT_DETAILS_FAIL',
CART_ADD_ITEM : 'CART_ADD_ITEM',
CART_REMOVE_ITEM : 'CART_REMOVE_ITEM',
CART_SAVE_SHIPPING_ADDRESS : 'CART_SAVE_SHIPPING_ADDRESS',
CART_SAVE_PAYMENT_METHOD: 'CART_SAVE_PAYMENT_METHOD',
CART_EMPTY: 'CART_EMPTY',
USER_SIGNIN_REQUEST : 'USER_SIGNIN_REQUEST',
USER_SIGNIN_SUCCESS : 'USER_SIGNIN_SUCCESS',
USER_SIGNIN_FAIL : 'USER_SIGNIN_FAIL',
USER_SIGNOUT : 'USER_SIGNOUT',
USER_REGISTER_REQUEST : 'USER_REGISTER_REQUEST',
USER_REGISTER_SUCCESS : 'USER_REGISTER_SUCCESS',
USER_REGISTER_FAIL : 'USER_REGISTER_FAIL',
ORDER_CREATE_REQUEST : 'ORDER_CREATE_REQUEST',
ORDER_CREATE_SUCCESS : 'ORDER_CREATE_SUCCESS',
ORDER_CREATE_FAIL : 'ORDER_CREATE_FAIL',
ORDER_CREATE_RESET : 'ORDER_CREATE_RESET'
};

export default actionTypes;